'use client';
import { useState, useEffect } from 'react';
import { PenTool, Plus, Clock, CheckCircle } from 'lucide-react';
import { useToast } from '@/components/Toast';
export default function ESignPage() {
  const { error: te, success: ts } = useToast();
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState<any>({title:'',documentUrl:'',recipients:''});
  useEffect(() => { load(); }, []);
  const load = async () => { setLoading(true); try { const r = await fetch('/api/esign',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); if(r.ok) setItems(await r.json()); } catch{} finally { setLoading(false); } };
  const save = async (e:React.FormEvent) => { e.preventDefault(); try { await fetch('/api/esign',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`},body:JSON.stringify(form)}); ts('تم الإرسال'); setShowModal(false); load(); } catch(e:any){te(e?.message);} };
  const sc:any = {PENDING:'#EAB308',SIGNED:'#22C55E',EXPIRED:'#EF4444'};
  return (<div style={{padding:'24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px',flexWrap:'wrap',gap:'16px'}}><div><h1 style={{fontSize:'24px',fontWeight:'bold',display:'flex',alignItems:'center',gap:'10px'}}><PenTool size={28} color="var(--primary)" /> التوقيع الإلكتروني</h1><p style={{color:'var(--text-muted)',marginTop:'4px',fontSize:'14px'}}>إرسال وتتبع طلبات التوقيع</p></div><button className="btn btn-primary" onClick={()=>{setForm({title:'',documentUrl:'',recipients:''});setShowModal(true);}}><Plus size={20} /> طلب توقيع</button></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:'16px',marginBottom:'24px'}}>{[{l:'إجمالي',v:items.length,c:'#6366F1'},{l:'في الانتظار',v:items.filter(i=>i.status==='PENDING').length,c:'#EAB308'},{l:'موقعة',v:items.filter(i=>i.status==='SIGNED').length,c:'#22C55E'}].map((s,i)=>(<div key={i} className="card" style={{padding:'16px',borderTop:`3px solid ${s.c}`}}><div style={{fontSize:'12px',color:'var(--text-muted)'}}>{s.l}</div><div style={{fontSize:'28px',fontWeight:'800',color:s.c,marginTop:'4px'}}>{s.v}</div></div>))}</div>
  {loading?<div style={{textAlign:'center',padding:'40px'}}>جاري التحميل...</div>:(<div className="card" style={{overflow:'auto'}}><table className="table"><thead><tr><th>المستند</th><th>المستلمين</th><th>الحالة</th><th>التوقيعات</th><th>التاريخ</th></tr></thead><tbody>{items.map(i=>(<tr key={i.id}><td style={{fontWeight:'600'}}>{i.title}</td><td style={{fontSize:'12px'}}>{i.recipients||'-'}</td><td><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:(sc[i.status]||'#94A3B8')+'20',color:sc[i.status]}}>{i.status==='PENDING'?'في الانتظار':i.status==='SIGNED'?'موقع':'منتهي'}</span></td><td>{i.logs?.length||0}</td><td style={{fontSize:'12px'}}>{new Date(i.createdAt).toLocaleDateString('ar-SA')}</td></tr>))}{items.length===0&&<tr><td colSpan={5} style={{textAlign:'center',padding:'30px',color:'var(--text-muted)'}}>لا توجد طلبات</td></tr>}</tbody></table></div>)}
  {showModal&&(<div className="modal-overlay"><div className="modal-content" style={{maxWidth:'500px'}}><div className="modal-header"><h2>طلب توقيع جديد</h2><button className="btn btn-ghost" onClick={()=>setShowModal(false)}>✕</button></div><div className="modal-body"><form onSubmit={save}><div className="input-group"><label className="input-label">عنوان المستند*</label><input className="input" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="input-group"><label className="input-label">رابط المستند</label><input className="input" dir="ltr" value={form.documentUrl} onChange={e=>setForm({...form,documentUrl:e.target.value})}/></div><div className="input-group"><label className="input-label">المستلمين (emails)</label><textarea className="input" rows={3} value={form.recipients} onChange={e=>setForm({...form,recipients:e.target.value})} placeholder="email1@x.com, email2@x.com"/></div><div style={{display:'flex',justifyContent:'flex-end',gap:'12px',marginTop:'20px'}}><button type="button" className="btn btn-ghost" onClick={()=>setShowModal(false)}>إلغاء</button><button type="submit" className="btn btn-primary">إرسال</button></div></form></div></div></div>)}</div>);
}
