'use client';
import { useState, useEffect } from 'react';
import { useTranslation } from '@/lib/i18n';
import { Truck, Plus } from 'lucide-react';
import { useToast } from '@/components/Toast';
export default function LogisticsPage() {
  const { lang } = useTranslation();
  const _t = (ar: string, en: string) => lang === 'ar' ? ar : en;
  const { error: te, success: ts } = useToast();
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState<any>({type:'OUTBOUND',origin:'',destination:'',weight:0,trackingNo:''});
  useEffect(() => { load(); }, []);
  const load = async () => { setLoading(true); try { const r = await fetch('/api/logistics/freight',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); if(r.ok) setItems(await r.json()); } catch{} finally { setLoading(false); } };
  const save = async (e:React.FormEvent) => { e.preventDefault(); try { await fetch('/api/logistics/freight',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`},body:JSON.stringify(form)}); ts('تم'); setShowModal(false); load(); } catch(e:any){te(e?.message);} };
  const sc:any = {DRAFT:'#94A3B8',BOOKED:'#3B82F6',IN_TRANSIT:'#EAB308',DELIVERED:'#22C55E',CANCELLED:'#EF4444'};
  return (<div style={{padding:'24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px',flexWrap:'wrap',gap:'16px'}}><div><h1 style={{fontSize:'24px',fontWeight:'bold',display:'flex',alignItems:'center',gap:'10px'}}><Truck size={28} color="var(--primary)" /> إدارة النقل واللوجستيات</h1><p style={{color:'var(--text-muted)',marginTop:'4px',fontSize:'14px'}}>TMS - الشحنات والنقل</p></div><button className="btn btn-primary" onClick={()=>{setForm({type:'OUTBOUND',origin:'',destination:'',weight:0,trackingNo:''});setShowModal(true);}}><Plus size={20}/> شحنة جديدة</button></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:'16px',marginBottom:'24px'}}>{[{l:'إجمالي الشحنات',v:items.length,c:'#6366F1'},{l:'قيد النقل',v:items.filter(i=>i.status==='IN_TRANSIT').length,c:'#EAB308'},{l:'تم التسليم',v:items.filter(i=>i.status==='DELIVERED').length,c:'#22C55E'}].map((s,i)=>(<div key={i} className="card" style={{padding:'16px',borderTop:`3px solid ${s.c}`}}><div style={{fontSize:'12px',color:'var(--text-muted)'}}>{s.l}</div><div style={{fontSize:'28px',fontWeight:'800',color:s.c,marginTop:'4px'}}>{s.v}</div></div>))}</div>
  {loading?<div style={{textAlign:'center',padding:'40px'}}>جاري التحميل...</div>:(<div className="card" style={{overflow:'auto'}}><table className="table"><thead><tr><th>رقم الشحنة</th><th>النوع</th><th>من</th><th>إلى</th><th>الوزن</th><th>التتبع</th><th>الحالة</th></tr></thead><tbody>{items.map(i=>(<tr key={i.id}><td style={{fontWeight:'600',fontFamily:'monospace'}}>{i.orderNo}</td><td>{i.type==='INBOUND'?'وارد':'صادر'}</td><td>{i.origin||'-'}</td><td>{i.destination||'-'}</td><td>{i.weight} kg</td><td style={{fontFamily:'monospace',fontSize:'12px'}}>{i.trackingNo||'-'}</td><td><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:(sc[i.status]||'#94A3B8')+'20',color:sc[i.status]}}>{i.status}</span></td></tr>))}{items.length===0&&<tr><td colSpan={7} style={{textAlign:'center',padding:'30px',color:'var(--text-muted)'}}>لا توجد شحنات</td></tr>}</tbody></table></div>)}
  {showModal&&(<div className="modal-overlay"><div className="modal-content" style={{maxWidth:'500px'}}><div className="modal-header"><h2>شحنة جديدة</h2><button className="btn btn-ghost" onClick={()=>setShowModal(false)}>✕</button></div><div className="modal-body"><form onSubmit={save}><div className="grid-2"><div className="input-group"><label className="input-label">النوع</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="OUTBOUND">صادر</option><option value="INBOUND">وارد</option></select></div><div className="input-group"><label className="input-label">الوزن (kg)</label><input className="input" type="number" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></div><div className="input-group"><label className="input-label">من*</label><input className="input" required value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}/></div><div className="input-group"><label className="input-label">إلى*</label><input className="input" required value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></div><div className="input-group" style={{gridColumn:'1/-1'}}><label className="input-label">رقم التتبع</label><input className="input" dir="ltr" value={form.trackingNo} onChange={e=>setForm({...form,trackingNo:e.target.value})}/></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:'12px',marginTop:'20px'}}><button type="button" className="btn btn-ghost" onClick={()=>setShowModal(false)}>إلغاء</button><button type="submit" className="btn btn-primary">حفظ</button></div></form></div></div></div>)}</div>);
}
