'use client';
import { useState, useEffect } from 'react';
import { CalendarDays, Plus, Users, MapPin } from 'lucide-react';
import { useToast } from '@/components/Toast';
export default function EventsPage() {
  const { error: te, success: ts } = useToast();
  const [events, setEvents] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState<any>({title:'',type:'WORKSHOP',location:'',startDate:'',endDate:'',capacity:100,ticketPrice:0});
  useEffect(() => { load(); }, []);
  const load = async () => { setLoading(true); try { const r = await fetch('/api/events',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); if(r.ok) setEvents(await r.json()); } catch{} finally { setLoading(false); } };
  const save = async (e:React.FormEvent) => { e.preventDefault(); try { await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`},body:JSON.stringify(form)}); ts('تم'); setShowModal(false); load(); } catch(e:any){te(e?.message);} };
  const sc:any = {UPCOMING:'#3B82F6',ONGOING:'#22C55E',COMPLETED:'#94A3B8',CANCELLED:'#EF4444'};
  return (<div style={{padding:'24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px',flexWrap:'wrap',gap:'16px'}}><div><h1 style={{fontSize:'24px',fontWeight:'bold',display:'flex',alignItems:'center',gap:'10px'}}><CalendarDays size={28} color="var(--primary)" /> إدارة الفعاليات</h1></div><button className="btn btn-primary" onClick={()=>{setForm({title:'',type:'WORKSHOP',location:'',startDate:'',endDate:'',capacity:100,ticketPrice:0});setShowModal(true);}}><Plus size={20} /> فعالية جديدة</button></div>
  {loading?<div style={{textAlign:'center',padding:'40px',color:'var(--text-muted)'}}>جاري التحميل...</div>:(<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(320px,1fr))',gap:'16px'}}>{events.map(ev=>(<div key={ev.id} className="card" style={{padding:'20px',borderTop:`3px solid ${sc[ev.status]||'#94A3B8'}`}}><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:(sc[ev.status]||'#94A3B8')+'20',color:sc[ev.status]}}>{ev.status}</span><h3 style={{fontSize:'18px',fontWeight:'700',margin:'8px 0'}}>{ev.title}</h3>{ev.location&&<div style={{fontSize:'13px',color:'var(--text-muted)',display:'flex',alignItems:'center',gap:'4px'}}><MapPin size={14}/>{ev.location}</div>}<div style={{display:'flex',justifyContent:'space-between',padding:'10px',background:'var(--bg-body)',borderRadius:'8px',marginTop:'12px'}}><span style={{display:'flex',alignItems:'center',gap:'4px',fontSize:'13px'}}><Users size={14}/>{ev._count?.registrations||0}/{ev.capacity}</span>{ev.ticketPrice>0&&<span style={{fontWeight:'700',color:'var(--primary)'}}>{ev.ticketPrice} ر.س</span>}</div></div>))}{events.length===0&&<div className="card" style={{padding:'40px',textAlign:'center',color:'var(--text-muted)',gridColumn:'1/-1'}}>لا توجد فعاليات</div>}</div>)}
  {showModal&&(<div className="modal-overlay"><div className="modal-content" style={{maxWidth:'600px'}}><div className="modal-header"><h2>فعالية جديدة</h2><button className="btn btn-ghost" onClick={()=>setShowModal(false)}>✕</button></div><div className="modal-body"><form onSubmit={save}><div className="grid-2"><div className="input-group" style={{gridColumn:'1/-1'}}><label className="input-label">الاسم*</label><input className="input" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="input-group"><label className="input-label">النوع</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="CONFERENCE">مؤتمر</option><option value="WORKSHOP">ورشة</option><option value="WEBINAR">ندوة</option></select></div><div className="input-group"><label className="input-label">الموقع</label><input className="input" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div><div className="input-group"><label className="input-label">بداية*</label><input className="input" type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></div><div className="input-group"><label className="input-label">نهاية*</label><input className="input" type="date" required value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:'12px',marginTop:'20px'}}><button type="button" className="btn btn-ghost" onClick={()=>setShowModal(false)}>إلغاء</button><button type="submit" className="btn btn-primary">حفظ</button></div></form></div></div></div>)}</div>);
}
