module.exports = {
  "sidebar.section.dashboard": "Dashboard",
  "sidebar.section.sales": "Sales & POS",
  "sidebar.section.purchases": "Purchases",
  "sidebar.section.inventory": "Inventory & WMS",
  "sidebar.section.manufacturing": "Manufacturing (MRP)",
  "sidebar.section.finance": "Finance & Accounting",
  "sidebar.section.crm": "CRM & Customers",
  "sidebar.section.hr": "HR & Payroll",
  "sidebar.section.enterprise": "Enterprise Modules",
  "sidebar.section.settings": "System Settings",
  "sidebar.item.dashboard": "Home Dashboard",
  "sidebar.item.copilot": "AI Copilot",
  "sidebar.item.cfo": "AI CFO",
  "sidebar.item.scm": "AI SCM",
  "sidebar.item.alerts": "Inbox & Alerts",
  "sidebar.item.pos": "POS Terminal",
  "sidebar.item.restaurant": "Restaurant POS",
  "sidebar.item.shifts": "Cashier Shifts",
  "sidebar.item.sales_invoices": "Tax Invoices",
  "sidebar.item.sales_history": "Sales History",
  "sidebar.item.sales_quotes": "Sales Quotations",
  "sidebar.item.sales_orders": "Sales Orders",
  "sidebar.item.delivery_notes": "Delivery Notes",
  "sidebar.item.sales_returns": "Sales Returns",
  "sidebar.item.recurring_invoices": "Recurring Contracts",
  "sidebar.item.sales_routes": "Sales Routes",
  "sidebar.item.commissions": "Commissions & Targets",
  "sidebar.item.purchase_reqs": "Purchase Requests (PR)",
  "sidebar.item.supplier_quotes": "Supplier RFQ",
  "sidebar.item.purchase_orders": "Purchase Orders (PO)",
  "sidebar.item.grn": "Goods Receipt Note (GRN)",
  "sidebar.item.purchases": "Purchase Invoices",
  "sidebar.item.purchase_returns": "Purchase Returns",
  "sidebar.item.lc": "Letters of Credit (LC)",
  "sidebar.item.products": "Products & Services",
  "sidebar.item.stock": "Stock Balances",
  "sidebar.item.movements": "Stock Item History",
  "sidebar.item.transfer": "Internal Stock Transfer",
  "sidebar.item.smart_transfer": "Smart Branch Transfers",
  "sidebar.item.adjustments": "Stock Adjustments",
  "sidebar.item.warehouses_setup": "Warehouses Setup",
  "sidebar.item.wms": "Smart WMS",
  "sidebar.item.barcodes": "Barcodes & Labels",
  "sidebar.item.batches": "Batches & Expiry",
  "sidebar.item.serials": "Serial Numbers",
  "sidebar.item.vision": "AI Stocktake Vision",
  "sidebar.item.mfg_bom": "Bills of Material (BOM)",
  "sidebar.item.advanced_mrp": "Advanced MRP Planning",
  "sidebar.item.qc": "Quality Control (QC)",
  "sidebar.item.coa": "Chart of Accounts (COA)",
  "sidebar.item.treasury": "Treasury & Funds",
  "sidebar.item.banks": "Banks & Reconciliation",
  "sidebar.item.papery": "Checks & Notes",
  "sidebar.item.vouchers": "Journal Entries",
  "sidebar.item.petty_expense": "Petty Cash",
  "sidebar.item.petty_funds": "Petty Cash Funds",
  "sidebar.item.fixed_assets": "Fixed Assets",
  "sidebar.item.budgets": "Cost Centers & Budgets",
  "sidebar.item.installments_sys": "Installments Management",
  "sidebar.item.fin_reports": "Financial Reports",
  "sidebar.item.customers": "Customers Directory",
  "sidebar.item.leads": "Leads & Prospects",
  "sidebar.item.loyalty_points": "Loyalty Points",
  "sidebar.item.gift_cards": "Gift Cards",
  "sidebar.item.coupons": "Discount Coupons",
  "sidebar.item.promotions": "Promotions & Offers",
  "sidebar.item.employees_data": "Employee Files",
  "sidebar.item.attendance_std": "Standard Attendance",
  "sidebar.item.payroll": "Payroll Generation",
  "sidebar.item.leaves": "Vacations & Leaves",
  "sidebar.item.loans": "Employee Loans",
  "sidebar.item.recruitment": "Recruitment & Onboarding",
  "sidebar.item.kpi": "Performance Appraisals",
  "sidebar.item.training": "Training & Courses",
  "sidebar.item.face_id": "AI Face Attendance",
  "sidebar.item.projects": "Project Management",
  "sidebar.item.real_estate": "Real Estate Management",
  "sidebar.item.leases": "Rental Contracts",
  "sidebar.item.fleet": "Fleet & Vehicles",
  "sidebar.item.fleet_trips": "Fleet Trips",
  "sidebar.item.schools": "Schools Management",
  "sidebar.item.classes": "Classes Management",
  "sidebar.item.credit_control": "B2B Credit Control",
  "sidebar.item.saas": "SaaS Subscription",
  "sidebar.item.branches_pos": "Branches & Devices",
  "sidebar.item.currencies": "Currencies & Rates",
  "sidebar.item.approvals": "Approval Workflows",
  "sidebar.item.wa": "WhatsApp Hub Setup",
  "sidebar.item.salla_int": "Salla Integration",
  "sidebar.item.sys_settings": "General System Settings",
  "sidebar.item.audit": "Audit & Logs",
  "sidebar.item.support": "Maintenance & Support",
  "sidebar.logout": "Logout"
}