const fs = require('fs');

const path = 'src/components/Sidebar.tsx';
let content = fs.readFileSync(path, 'utf8');

// The English terms mistakenly placed in the Arabic section
const fixes = {
    "'i.cfo_dashboard': 'CFO Dashboard'": "'i.cfo_dashboard': 'لوحة المدير المالي'",
    "'i.wave_picking': 'Wave Picking (WMS)'": "'i.wave_picking': 'التقاط موجي (WMS)'",
    "'i.wms_map': 'WMS Visual Map'": "'i.wms_map': 'خريطة المستودع المرئية'",
    "'i.pos_accountant': 'POS Accountant'": "'i.pos_accountant': 'محاسب الكاشير'",
    "'i.sales_analytics': 'Sales BI Analytics'": "'i.sales_analytics': 'تحليلات مبيعات BI'",
    "'i.smart_map': 'Smart Field Map'": "'i.smart_map': 'خريطة ميدانية ذكية'",
    "'i.pharmacy_mgr': 'Pharmacy Manager'": "'i.pharmacy_mgr': 'مدير الصيدلية'",
    "'i.drug_interact': 'Drug Interactions'": "'i.drug_interact': 'تداخلات الأدوية'",
    "'i.fifo': 'FIFO / FEFO Manager'": "'i.fifo': 'إدارة وارد أولاً'",
    "'i.cfo_dash': 'CFO Dashboard'": "'i.cfo_dash': 'لوحة تحكم مالية'",
    "'i.leave_mgmt': 'Leave Management'": "'i.leave_mgmt': 'إدارة الإجازات'",
    "'i.doc_expiry': 'Document Expiry Alerts'": "'i.doc_expiry': 'تنبيهات وثائق'",
    "'i.cash_flow': 'Cash Flow Forecasting'": "'i.cash_flow': 'توقعات نقدية'",
    "'i.consolidation': 'Financial Consolidation'": "'i.consolidation': 'توحيد مالي'",
    "'i.fx_reval': 'FX Revaluation'": "'i.fx_reval': 'تقييم العملات'",
    "'i.allocation': 'Cost Allocation'": "'i.allocation': 'توزيع التكاليف'",
    "'i.budget_ctrl': 'Budget Control'": "'i.budget_ctrl': 'رقابة الميزانية'",
    "'i.supplier_contracts': 'Supplier Contracts'": "'i.supplier_contracts': 'عقود الموردين'",
    "'i.price_compare': 'Price Comparison'": "'i.price_compare': 'مقارنة الأسعار'",
    "'i.mrp_dash': 'MRP Dashboard'": "'i.mrp_dash': 'لوحة التصنيع'",
    "'i.mfg_qc': 'Manufacturing QC'": "'i.mfg_qc': 'جودة التصنيع'",
    "'i.fleet_gps': 'Fleet GPS Tracking'": "'i.fleet_gps': 'تتبع الأسطول'",
    "'i.help_desk': 'Help Desk'": "'i.help_desk': 'الدعم الفني'",
    "'i.cx_nps': 'CX / NPS'": "'i.cx_nps': 'تقييم العملاء'",
    "'i.key_accounts': 'Key Accounts (KAM)'": "'i.key_accounts': 'الحسابات الكبرى'",
    "'i.portfolio': 'Project Portfolio'": "'i.portfolio': 'محفظة المشاريع'",
    "'i.marketing_analytics': 'Marketing Analytics'": "'i.marketing_analytics': 'تحليلات التسويق'",
    "'i.ai_demand': 'AI Demand Forecast'": "'i.ai_demand': 'توقع الطلب AI'",
    "'i.ai_coach': 'AI Sales Coach'": "'i.ai_coach': 'مدرب المبيعات AI'",
    "'i.siem': 'Security (SIEM)'": "'i.siem': 'المركز الأمني'",
    "'i.backup': 'System Backup'": "'i.backup': 'نسخ احتياطي'",
    "'i.profit_centers': 'Profit Centers'": "'i.profit_centers': 'مراكز الربحية'",
    "'i.segments': 'Segments'": "'i.segments': 'القطاعات'",
    "'i.copa': 'Profitability Analysis (CO-PA)'": "'i.copa': 'تحليل الربحية'",
    "'i.copa_rules': 'Cost Allocation Rules'": "'i.copa_rules': 'قواعد التكلفة'",
    "'i.num_seq': 'Number Sequences'": "'i.num_seq': 'تسلسل الأرقام'",
    "'i.state_machine': 'Document States'": "'i.state_machine': 'حالات المستند'",
    "'i.field_audit': 'Field Audit Trail'": "'i.field_audit': 'سجل التعديلات'",
    "'i.period_close': 'Period Close'": "'i.period_close': 'إغلاق الفترات'",
    "'i.wps': 'Wage Protection System (WPS)'": "'i.wps': 'نظام حماية الأجور'",
    "'i.bank_recon_auto': 'Auto Bank Reconciliation'": "'i.bank_recon_auto': 'مطابقة بنكية'",
    "'i.dunning': 'Dunning & Collections'": "'i.dunning': 'التحصيل والمطالبات'",
    "'i.three_way': '3-Way Matching'": "'i.three_way': 'المطابقة الثلاثية'",
    "'i.bpm': 'BPM Engine'": "'i.bpm': 'محرك سير العمل'",
    "'i.payment_run': 'Payment Run (F110)'": "'i.payment_run': 'دفعة مجمعة'",
    "'i.ecl': 'Expected Credit Loss (ECL)'": "'i.ecl': 'الخسائر المتوقعة'",
    "'i.std_cost': 'Standard Costing'": "'i.std_cost': 'تكاليف معيارية'",
    "'i.subcontracting': 'Subcontracting'": "'i.subcontracting': 'تصنيع خارجي'",
    "'i.quality_mgmt': 'Quality Management (CAPA)'": "'i.quality_mgmt': 'إدارة الجودة'",
    "'i.multi_book': 'Multi-Book (Multi-GAAP)'": "'i.multi_book': 'الدفاتر المتعددة'",
    "'i.custom_fields': 'Custom Fields'": "'i.custom_fields': 'حقول مخصصة'",
    "'s.saudi_compliance': '🇸🇦 Saudi Compliance'": "'s.saudi_compliance': '🇸🇦 الامتثال السعودي'",
    "'i.qiwa_sync': 'Qiwa Integration'": "'i.qiwa_sync': 'تزامن قوى'",
    "'i.saudization': 'Saudization & Nitaqat'": "'i.saudization': 'نطاقات والسعودة'",
    "'i.qiwa_contracts': 'Work Contracts (Qiwa)'": "'i.qiwa_contracts': 'عقود العمل'",
    "'i.nitaqat_sim': 'Nitaqat Simulator'": "'i.nitaqat_sim': 'محاكي نطاقات'",
    "'i.pdpl_dsr': 'Data Subject Requests (PDPL)'": "'i.pdpl_dsr': 'طلبات PDPL'",
    "'i.pdpl_breach': 'Breach Incidents'": "'i.pdpl_breach': 'الاختراقات'",
    "'i.vat_categories': 'VAT Categories'": "'i.vat_categories': 'فئات ضريبية'",
    "'i.wht_form14': 'WHT Form 14'": "'i.wht_form14': 'نموذج 14 استقطاع'",
    "'i.mudad_compliance': 'Mudad Compliance'": "'i.mudad_compliance': 'التزام مدد'",
    "'i.zakat_assessment': 'Zakat Assessment'": "'i.zakat_assessment': 'تقييم الزكاة'",
    "'s.pharmacy': '💊 Pharmacy & Healthcare'": "'s.pharmacy': '💊 الصيدلية'",
    "'s.new_modules': '🚀 New Modules'": "'s.new_modules': '🚀 وحدات جديدة'",
    "'s.v3_verticals': '🏢 Industry Verticals V3'": "'s.v3_verticals': '🏢 تخصصات V3'",
    "'i.v3_retail': 'Retail Dashboard'": "'i.v3_retail': 'تجزئة'",
    "'i.v3_restaurant': 'Restaurant Dashboard'": "'i.v3_restaurant': 'مطاعم'",
    "'i.v3_mfg': 'Mfg Dashboard'": "'i.v3_mfg': 'تصنيع'",
    "'i.v3_construction': 'Const. Dashboard'": "'i.v3_construction': 'مقاولات'",
    "'i.v3_clinic': 'Clinic Dashboard'": "'i.v3_clinic': 'عيادات'",
    "'i.v3_school': 'School Dashboard'": "'i.v3_school': 'مدارس'",
    "'i.v3_realestate': 'Real Estate Dash'": "'i.v3_realestate': 'أملاك'",
    "'i.v3_distribution': 'Distribution Dash'": "'i.v3_distribution': 'توزيع'",
    "'i.v3_services': 'Services Dashboard'": "'i.v3_services': 'خدمات'",
    "'i.v3_retail_pos': 'Multi-Branch POS'": "'i.v3_retail_pos': 'نقطة بيع متعددة'",
    "'i.v3_restaurant_kds': 'Kitchen Display (KDS)'": "'i.v3_restaurant_kds': 'شاشة مطبخ'",
    "'i.v3_mfg_mrp': 'MRP Engine'": "'i.v3_mfg_mrp': 'محرك MRP'",
    "'i.v3_construction_boq': 'BOQ & Progress Billing'": "'i.v3_construction_boq': 'مستخلصات'",
    "'i.v3_clinic_emr': 'Electronic Medical Records'": "'i.v3_clinic_emr': 'ملف طبي'",
    "'i.v3_school_sis': 'Student Information System'": "'i.v3_school_sis': 'نظام طلاب'",
    "'i.v3_realestate_leases': 'Leases & Property'": "'i.v3_realestate_leases': 'عقود أملاك'",
    "'i.v3_distribution_wms': 'Advanced WMS'": "'i.v3_distribution_wms': 'مستودع متقدم'",
    "'i.v3_services_timesheet': 'Timesheets & Expenses'": "'i.v3_services_timesheet': 'مصروفات وقت'",
    "'i.webhooks': 'Webhooks'": "'i.webhooks': 'تكامل Webhook'",
    "'i.credit_check': 'Credit Check'": "'i.credit_check': 'فحص ائتمان'",
    "'i.cash_forecast': 'Cash Forecast'": "'i.cash_forecast': 'توقع سيولة'",
    "'i.number_sequences': 'Number Sequences'": "'i.number_sequences': 'تسلسلات الأرقام'",
    "'i.cpq': 'Configure-Price-Quote'": "'i.cpq': 'تسعير متقدم (CPQ)'",
    "'i.rebates': 'Rebate Programs'": "'i.rebates': 'برامج المكافآت'",
    "'i.sales_forecast': 'Sales Forecast'": "'i.sales_forecast': 'توقع مبيعات'",
    "'i.vendor_scorecard': 'Vendor Scorecard'": "'i.vendor_scorecard': 'تقييم موردين'",
    "'i.aps_scheduler': 'APS Scheduler'": "'i.aps_scheduler': 'مجدول متقدم'",
    "'i.project_evm': 'Earned Value (EVM)'": "'i.project_evm': 'قيمة مكتسبة'",
    "'i.wave_picking': 'Wave Picking (WMS)'": "'i.wave_picking': 'التقاط موجي'",
    "'i.mes_oee': 'OEE Dashboard'": "'i.mes_oee': 'كفاءة الآلات'",
    "'i.bi_cube': 'BI Analytics'": "'i.bi_cube': 'تحليلات ذكية'",
    "'i.nlq': 'Ask System (NLQ)'": "'i.nlq': 'تحدث مع النظام'",
    "'i.spend_analytics': 'Spend Analytics'": "'i.spend_analytics': 'تحليل إنفاق'",
    "'i.service_sla': 'Service SLA'": "'i.service_sla': 'اتفاقية مستوى الخدمة'",
    "'i.prev_maintenance': 'Preventive Maintenance'": "'i.prev_maintenance': 'صيانة وقائية'",
    "'i.sso_saml': 'SSO / SAML'": "'i.sso_saml': 'دخول موحد'",
    "'i.aging_report': 'Aging Reports'": "'i.aging_report': 'تقادم أرصدة'",
    "'i.kanban_board': 'Kanban Board'": "'i.kanban_board': 'لوحة كانبان'",
    "'i.timesheet': 'Timesheet'": "'i.timesheet': 'سجل ساعات العمل'",
    "'i.self_service': 'Employee Portal'": "'i.self_service': 'بوابة خدمة ذاتية'",
    "'i.contracts_mgmt': 'Contract Management'": "'i.contracts_mgmt': 'إدارة عقود'",
    "'i.vendor_portal_page': 'Vendor Portal'": "'i.vendor_portal_page': 'بوابة الموردين'",
    "'i.workflow_builder': 'Workflow Builder'": "'i.workflow_builder': 'مصمم سير العمل'",
    "'i.print_templates': 'Print Templates'": "'i.print_templates': 'قوالب الطباعة'",
    "'i.dashboard_builder': 'Dashboard Builder'": "'i.dashboard_builder': 'مصمم لوحات التحكم'",
    "'i.import_export': 'Import / Export'": "'i.import_export': 'استيراد/تصدير'",
    "'i.dms': 'Document Management'": "'i.dms': 'إدارة وثائق'",
    "'i.calendar': 'Calendar'": "'i.calendar': 'تقويم'",
    "'i.pivot_table': 'Pivot Table'": "'i.pivot_table': 'جدول محوري'",
    "'i.customer360': 'Customer 360°'": "'i.customer360': 'العميل بـ 360'",
    "'i.reorder_rules': 'Reorder Rules'": "'i.reorder_rules': 'قواعد إعادة الطلب'",
    "'i.notifications': 'Notifications'": "'i.notifications': 'إشعارات'",
    "'i.expense_reports': 'Expense Reports'": "'i.expense_reports': 'تقارير المصروفات'",
    "'i.org_chart': 'Org Chart'": "'i.org_chart': 'هيكل تنظيمي'",
    "'i.global_search': 'Global Search'": "'i.global_search': 'بحث شامل'",
    "'i.chatter': 'Comments'": "'i.chatter': 'محادثات'",
    "'i.deferred_rev': 'Deferred Revenue'": "'i.deferred_rev': 'إيرادات مؤجلة'",
    "'i.shipping': 'Shipping Carriers'": "'i.shipping': 'شركات شحن'",
    "'i.campaigns': 'Marketing Campaigns'": "'i.campaigns': 'حملات تسويقية'",
    "'i.tickets': 'Support Tickets'": "'i.tickets': 'تذاكر الدعم'",
    "'i.bi_dashboard': 'BI Dashboard'": "'i.bi_dashboard': 'لوحة الذكاء'",
    "'i.budget_scenarios': 'Budget Scenarios'": "'i.budget_scenarios': 'سيناريوهات الميزانية'",
    "'i.ecommerce': 'E-Commerce'": "'i.ecommerce': 'متجر إلكتروني'",
    "'i.contract_templates': 'Contract Templates'": "'i.contract_templates': 'قوالب العقود'",
    "'i.sub_plans': 'Subscription Plans'": "'i.sub_plans': 'باقات الاشتراكات'",
    "'i.ecommerce_stores': 'E-Commerce Stores'": "'i.ecommerce_stores': 'متاجر إلكترونية'",
    "'i.grc': 'GRC & Risk'": "'i.grc': 'الحوكمة والمخاطر'",
    "'i.knowledge': 'Knowledge Base'": "'i.knowledge': 'قاعدة المعرفة'",
    "'i.events': 'Events'": "'i.events': 'فعاليات'",
    "'i.esign': 'E-Signature'": "'i.esign': 'توقيع إلكتروني'",
    "'i.cmms': 'Maintenance (CMMS)'": "'i.cmms': 'نظام صيانة'",
    "'i.logistics': 'Logistics & TMS'": "'i.logistics': 'إدارة النقليات'",
    "'i.lms': 'LMS / eLearning'": "'i.lms': 'تعلم إلكتروني'",
    "'i.audits': 'Internal Audits'": "'i.audits': 'تدقيق داخلي'",
    "'i.maint_wo': 'Maintenance Work Orders'": "'i.maint_wo': 'أوامر صيانة'",
    "'i.carriers': 'Carriers & Rates'": "'i.carriers': 'أجور النقل'",
    "'i.planning': 'Planning & Schedule'": "'i.planning': 'التخطيط والجدولة'",
    "'i.portal': 'Customer Portal'": "'i.portal': 'بوابة العملاء'",
    "'i.rental': 'Rental Management'": "'i.rental': 'إدارة تأجير'",
    "'i.field_service': 'Field Service'": "'i.field_service': 'الخدمات الميدانية'",
    "'i.pos_offline': 'POS Offline'": "'i.pos_offline': 'الكاشير المحلي'"
};

// Only replace inside the `ar:` block
const arStart = content.indexOf('ar: {');
const enStart = content.indexOf('en: {');

if (arStart !== -1 && enStart !== -1) {
    let arBlock = content.substring(arStart, enStart);
    for (const [eng, arb] of Object.entries(fixes)) {
        arBlock = arBlock.replace(eng, arb);
    }
    content = content.substring(0, arStart) + arBlock + content.substring(enStart);
    fs.writeFileSync(path, content, 'utf8');
    console.log('✅ Fixed English strings in Arabic block!');
} else {
    console.log('❌ Could not find block');
}
