const fs = require('fs');

const hiMappings = {
    'sidebar.section.dashboard': 'डैशबोर्ड',
    'sidebar.section.sales': 'बिक्री और पीओएस',
    'sidebar.section.purchases': 'खरीद',
    'sidebar.section.inventory': 'इन्वेंटरी',
    'sidebar.section.manufacturing': 'विनिर्माण (MRP)',
    'sidebar.section.finance': 'वित्त और लेखा',
    'sidebar.section.crm': 'ग्राहक और सीआरएम',
    'sidebar.section.hr': 'मानव संसाधन',
    'sidebar.section.enterprise': 'उद्यम प्रणालियाँ',
    'sidebar.section.settings': 'सेटिंग्स',
    'sidebar.item.copilot': 'एआई कोपायलट',
    'sidebar.item.cfo': 'एआई सीएफओ',
    'sidebar.item.scm': 'एआई एससीएम',
    'sidebar.item.alerts': 'इनबॉक्स और अलर्ट',
    'sidebar.item.pos': 'पीओएस',
    'sidebar.item.restaurant': 'रेस्तरां पीओएस',
    'sidebar.item.shifts': 'शिफ्ट',
    'sidebar.item.sales_history': 'चालान इतिहास',
    'sidebar.item.sales_quotes': 'कोटेशन',
    'sidebar.item.sales_orders': 'बिक्री आदेश',
    'sidebar.item.delivery_notes': 'वितरण नोट',
    'sidebar.item.sales_returns': 'बिक्री वापसी',
    'sidebar.item.recurring_invoices': 'आवर्ती चालान',
    'sidebar.item.sales_routes': 'बिक्री मार्ग',
    'sidebar.item.commissions': 'कमीशन और लक्ष्य',
    'sidebar.item.purchase_reqs': 'खरीद मांग',
    'sidebar.item.supplier_quotes': 'आपूर्तिकर्ता कोटेशन',
    'sidebar.item.purchase_orders': 'खरीद आदेश',
    'sidebar.item.grn': 'सामान प्राप्ति (GRN)',
    'sidebar.item.payable': 'देय खाते',
    'sidebar.item.purchase_returns': 'खरीद वापसी',
    'sidebar.item.lc': 'लेटर ऑफ क्रेडिट',
    'sidebar.item.products': 'उत्पाद',
    'sidebar.item.stock': 'स्टॉक बैलेंस',
    'sidebar.item.movements': 'आइटम मूवमेंट',
    'sidebar.item.transfer': 'स्टॉक ट्रांसफर',
    'sidebar.item.smart_transfer': 'स्मार्ट ट्रांसफर',
    'sidebar.item.adjustments': 'स्टॉक समायोजन',
    'sidebar.item.warehouses_setup': 'गोदाम सेटअप',
    'sidebar.item.wms': 'स्मार्ट WMS',
    'sidebar.item.barcodes': 'बारकोड',
    'sidebar.item.batches': 'बैच',
    'sidebar.item.serials': 'सीरियल नंबर',
    'sidebar.item.vision': 'विज़न स्टॉकटेक',
    'sidebar.item.mfg_bom': 'विनिर्माण और BOM',
    'sidebar.item.advanced_mrp': 'उन्नत MRP',
    'sidebar.item.qc': 'गुणवत्ता नियंत्रण',
    'sidebar.item.coa': 'खातों का चार्ट',
    'sidebar.item.treasury': 'ट्रेजरी',
    'sidebar.item.banks': 'बैंक',
    'sidebar.item.receivables': 'प्राप्य और देय',
    'sidebar.item.vouchers': 'रसीद और वाउचर',
    'sidebar.item.petty_expense': 'छोटे खर्च',
    'sidebar.item.petty_funds': 'पेटी फंड',
    'sidebar.item.fixed_assets': 'अचल संपत्ति',
    'sidebar.item.budgets': 'बजट',
    'sidebar.item.installments_sys': 'किस्तें',
    'sidebar.item.fin_reports': 'वित्तीय रिपोर्ट',
    'sidebar.item.customers': 'ग्राहक डेटाबेस',
    'sidebar.item.leads': 'सेल्स लीड्स',
    'sidebar.item.loyalty_points': 'लॉयल्टी पॉइंट',
    'sidebar.item.gift_cards': 'गिफ्ट कार्ड',
    'sidebar.item.coupons': 'कूपन',
    'sidebar.item.promotions': 'ऑफर और छूट',
    'sidebar.item.employees_data': 'कर्मचारी डेटा',
    'sidebar.item.attendance_std': 'उपस्थिति',
    'sidebar.item.face_id': 'फेस आईडी उपस्थिति',
    'sidebar.item.payroll': 'पेरोल',
    'sidebar.item.leaves': 'छुट्टियां',
    'sidebar.item.loans': 'ऋण',
    'sidebar.item.recruitment': 'भर्ती',
    'sidebar.item.kpi': 'केपीआई',
    'sidebar.item.training': 'प्रशिक्षण',
    'sidebar.item.projects': 'परियोजनाएं',
    'sidebar.item.real_estate': 'अचल संपत्ति',
    'sidebar.item.leases': 'किराया अनुबंध',
    'sidebar.item.fleet': 'परिवहन बेड़ा',
    'sidebar.item.fleet_trips': 'बेड़े की यात्राएं',
    'sidebar.item.schools': 'स्कूल सिस्टम',
    'sidebar.item.classes': 'कक्षाएं',
    'sidebar.item.credit_control': 'क्रेडिट कंट्रोल',
    'sidebar.item.saas': 'SaaS पैनल',
    'sidebar.item.branches_pos': 'शाखाएँ और पीओएस',
    'sidebar.item.currencies': 'मुद्रा प्रबंधन',
    'sidebar.item.approvals': 'अनुमोदन प्रणाली',
    'sidebar.item.regions': 'भौगोलिक क्षेत्र',
    'sidebar.item.users': 'उपयोगकर्ता अधिकार',
    'sidebar.item.health': 'सिस्टम स्वास्थ्य',
    'sidebar.item.wa': 'WhatsApp बॉट',
    'sidebar.item.salla_int': 'सल्ला',
    'sidebar.item.sys_settings': 'सामान्य सेटिंग्स',
    'sidebar.item.audit': 'ऑडिट लॉग',
    'sidebar.item.support': 'समर्थन'
};

const bnMappings = {
    'sidebar.section.dashboard': 'ড্যাশবোর্ড',
    'sidebar.section.sales': 'বিক্রি এবং পিওএস',
    'sidebar.section.purchases': 'ক্রয়',
    'sidebar.section.inventory': 'ইনভেন্টরি',
    'sidebar.section.manufacturing': 'ম্যানুফ্যাকচারিং',
    'sidebar.section.finance': 'ফাইন্যান্স',
    'sidebar.section.crm': 'কাস্টমারস (CRM)',
    'sidebar.section.hr': 'এইচআর এবং পে-রোল',
    'sidebar.section.enterprise': 'এন্টারপ্রাইজ',
    'sidebar.section.settings': 'সেটিংস',
    'sidebar.item.copilot': 'এআই কোপাইলট',
    'sidebar.item.cfo': 'এআই সিএফও',
    'sidebar.item.scm': 'এআই এসসিএম',
    'sidebar.item.alerts': 'ইনবক্স এবং অ্যালার্ট',
    'sidebar.item.pos': 'পিওএস',
    'sidebar.item.restaurant': 'রেস্টুরেন্ট পিওএস',
    'sidebar.item.shifts': 'ক্যাশিয়ার শিফট',
    'sidebar.item.sales_invoices': 'সেলস ইনভয়েস',
    'sidebar.item.sales_history': 'ইনভয়েস হিস্ট্রি',
    'sidebar.item.sales_quotes': 'কোটেশন',
    'sidebar.item.sales_orders': 'অর্ডার',
    'sidebar.item.delivery_notes': 'ডেলিভারি নোট',
    'sidebar.item.sales_returns': 'রিটার্ন',
    'sidebar.item.recurring_invoices': 'পুনরাবৃত্ত বিল',
    'sidebar.item.sales_routes': 'রুট',
    'sidebar.item.commissions': 'কমিশন',
    'sidebar.item.purchase_reqs': 'রিকুইজিশন',
    'sidebar.item.supplier_quotes': 'কোটস',
    'sidebar.item.purchase_orders': 'অর্ডার',
    'sidebar.item.grn': 'জিআরএন',
    'sidebar.item.payable': 'পেয়েবলস',
    'sidebar.item.purchase_returns': 'রিটার্ন',
    'sidebar.item.lc': 'এলসি (LC)',
    'sidebar.item.products': 'পণ্য',
    'sidebar.item.stock': 'স্টক ব্যালেন্স',
    'sidebar.item.movements': 'স্টক মুভমেন্ট',
    'sidebar.item.transfer': 'ট্রান্সফার',
    'sidebar.item.smart_transfer': 'স্মার্ট ট্রান্সফার',
    'sidebar.item.adjustments': 'অ্যাডজাস্টমেন্ট',
    'sidebar.item.warehouses_setup': 'গুদাম',
    'sidebar.item.wms': 'স্মার্ট ডব্লিউএমএস',
    'sidebar.item.barcodes': 'বারকোড',
    'sidebar.item.batches': 'ব্যাচ',
    'sidebar.item.serials': 'সিরিয়াল',
    'sidebar.item.vision': 'ভিশন এআই',
    'sidebar.item.mfg_bom': 'বিএমও (BOM)',
    'sidebar.item.advanced_mrp': 'অ্যাডভান্সড এমআরপি',
    'sidebar.item.qc': 'কোয়ালিটি কন্ট্রোল',
    'sidebar.item.coa': 'অ্যাকাউন্টস',
    'sidebar.item.treasury': 'ট্রেজারি',
    'sidebar.item.banks': 'ব্যাংক',
    'sidebar.item.receivables': 'রিসিভাবলস',
    'sidebar.item.vouchers': 'ভাউচার',
    'sidebar.item.petty_expense': 'খরচ',
    'sidebar.item.petty_funds': 'তহবিল',
    'sidebar.item.fixed_assets': 'স্থায়ী সম্পদ',
    'sidebar.item.budgets': 'বাজেট',
    'sidebar.item.installments_sys': 'কিস্তি',
    'sidebar.item.fin_reports': 'রিপোর্ট',
    'sidebar.item.customers': 'কাস্টমার ডাটাবেস',
    'sidebar.item.leads': 'লিডস',
    'sidebar.item.loyalty_points': 'লয়ালটি',
    'sidebar.item.gift_cards': 'গিফট কার্ড',
    'sidebar.item.coupons': 'কুপন',
    'sidebar.item.promotions': 'প্রমোশন',
    'sidebar.item.employees_data': 'কর্মী',
    'sidebar.item.attendance_std': 'উপস্থিতি',
    'sidebar.item.face_id': 'ফেইস আইডি',
    'sidebar.item.payroll': 'পে-রোল',
    'sidebar.item.leaves': 'ছুটি',
    'sidebar.item.loans': 'ঋণ',
    'sidebar.item.recruitment': 'নিয়োগ',
    'sidebar.item.kpi': 'কেপিআই',
    'sidebar.item.training': 'প্রশিক্ষণ',
    'sidebar.item.projects': 'প্রকল্প',
    'sidebar.item.real_estate': 'এস্টেট',
    'sidebar.item.leases': 'লিজ',
    'sidebar.item.fleet': 'ফ্লিট',
    'sidebar.item.fleet_trips': 'ট্রিপস',
    'sidebar.item.schools': 'স্কুল',
    'sidebar.item.classes': 'ক্লাস',
    'sidebar.item.credit_control': 'ক্রেডিট কন্ট্রোল',
    'sidebar.item.saas': 'সাস ప্যানেল',
    'sidebar.item.branches_pos': 'ব্রাঞ্চ',
    'sidebar.item.currencies': 'কারেন্সি',
    'sidebar.item.approvals': 'অ্যাপ্রুভালস',
    'sidebar.item.regions': 'অঞ্চল',
    'sidebar.item.users': 'পারমিশন',
    'sidebar.item.health': 'হেলথ',
    'sidebar.item.wa': 'হোয়াটসঅ্যাপ',
    'sidebar.item.salla_int': 'সাল্লা',
    'sidebar.item.sys_settings': 'সেটিংস',
    'sidebar.item.audit': 'অডিট',
    'sidebar.item.support': 'সাপোর্ট'
};

const urMappings = {
    'sidebar.section.dashboard': 'ڈیش بورڈ',
    'sidebar.section.sales': 'سیلز اور پی او ایس',
    'sidebar.section.purchases': 'خریداری',
    'sidebar.section.inventory': 'انوینٹری اور گودام',
    'sidebar.section.manufacturing': 'مینوفیکچرنگ (MRP)',
    'sidebar.section.finance': 'مالیات اور اکاؤنٹنگ',
    'sidebar.section.crm': 'کسٹمرز (CRM)',
    'sidebar.section.hr': 'ایچ آر اور پے رول',
    'sidebar.section.enterprise': 'انٹرپرائز',
    'sidebar.section.settings': 'ترتیبات',
    'sidebar.item.copilot': 'اے آئی کوپائلٹ',
    'sidebar.item.cfo': 'اے آئی سی ایف او',
    'sidebar.item.scm': 'اے آئی ایس سی ایم',
    'sidebar.item.alerts': 'ان باکس اور الرٹس',
    'sidebar.item.pos': 'پی او ایس',
    'sidebar.item.restaurant': 'ریسٹورنٹ پی او ایس',
    'sidebar.item.shifts': 'کیشیئر شفٹ',
    'sidebar.item.sales_invoices': 'ٹیکس سیلز انوائس',
    'sidebar.item.sales_history': 'انوائس ہسٹری',
    'sidebar.item.sales_quotes': 'سیلز کوٹیشن',
    'sidebar.item.sales_orders': 'سیلز آرڈرز',
    'sidebar.item.delivery_notes': 'ڈلیوری نوٹس',
    'sidebar.item.sales_returns': 'سیلز ریٹرن',
    'sidebar.item.recurring_invoices': 'ریکرنگ انوائسز',
    'sidebar.item.sales_routes': 'سیلز روٹس',
    'sidebar.item.commissions': 'کمیشن',
    'sidebar.item.purchase_reqs': 'پی آر (PR)',
    'sidebar.item.supplier_quotes': 'سپلائر کوٹس',
    'sidebar.item.purchase_orders': 'پرچیز آرڈرز (PO)',
    'sidebar.item.grn': 'جی آر این (GRN)',
    'sidebar.item.payable': 'پے ایبلز',
    'sidebar.item.purchase_returns': 'پرچیز ریٹرن',
    'sidebar.item.lc': 'ایل سی (LC)',
    'sidebar.item.products': 'پروڈکٹس',
    'sidebar.item.stock': 'موجودہ اسٹاک',
    'sidebar.item.movements': 'آئٹم موومنٹ',
    'sidebar.item.transfer': 'اسٹاک ٹرانسفر',
    'sidebar.item.smart_transfer': 'سمارٹ ٹرانسفر',
    'sidebar.item.adjustments': 'اسٹاک ایڈجسٹمنٹ',
    'sidebar.item.warehouses_setup': 'گودام کا سیٹ اپ',
    'sidebar.item.wms': 'سمارٹ WMS',
    'sidebar.item.barcodes': 'بارکوڈز',
    'sidebar.item.batches': 'بیچ اور ایکسپائری',
    'sidebar.item.serials': 'سیریل نمبرز',
    'sidebar.item.vision': 'ویژن اسٹاک ٹیک',
    'sidebar.item.mfg_bom': 'مینوفیکچرنگ اور BOM',
    'sidebar.item.advanced_mrp': 'ایڈوانسڈ MRP',
    'sidebar.item.qc': 'کوالٹی کنٹرول',
    'sidebar.item.coa': 'چارٹ آف اکاؤنٹس',
    'sidebar.item.treasury': 'ٹریژری اور لیکویڈیٹی',
    'sidebar.item.banks': 'بینک',
    'sidebar.item.receivables': 'ریسیو ایبلز',
    'sidebar.item.vouchers': 'واؤچرز',
    'sidebar.item.petty_expense': 'پیٹی اخراجات',
    'sidebar.item.petty_funds': 'پیٹی فنڈز',
    'sidebar.item.fixed_assets': 'فکسڈ اثاثے',
    'sidebar.item.budgets': 'بجٹ',
    'sidebar.item.installments_sys': 'قسطیں',
    'sidebar.item.fin_reports': 'مالیاتی رپورٹس',
    'sidebar.item.customers': 'کسٹمر ڈیٹا بیس',
    'sidebar.item.leads': 'سیلز لیڈز',
    'sidebar.item.loyalty_points': 'لائلٹی پوائنٹس',
    'sidebar.item.gift_cards': 'گفٹ کارڈز',
    'sidebar.item.coupons': 'کوپنز',
    'sidebar.item.promotions': 'پروموشنز',
    'sidebar.item.employees_data': 'ملازمین',
    'sidebar.item.attendance_std': 'حاضری',
    'sidebar.item.face_id': 'فیس آئی ڈی حاضری',
    'sidebar.item.payroll': 'پے رول',
    'sidebar.item.leaves': 'چھٹیاں',
    'sidebar.item.loans': 'قرضے',
    'sidebar.item.recruitment': 'بھرتی',
    'sidebar.item.kpi': 'کے پی آئی (KPI)',
    'sidebar.item.training': 'ٹریننگ',
    'sidebar.item.projects': 'پروجیکٹس',
    'sidebar.item.real_estate': 'ریل اسٹیٹ',
    'sidebar.item.leases': 'لیز معاہدے',
    'sidebar.item.fleet': 'فلیٹ',
    'sidebar.item.fleet_trips': 'فلیٹ ٹرپس',
    'sidebar.item.schools': 'اسکول سسٹم',
    'sidebar.item.classes': 'کلاسز',
    'sidebar.item.credit_control': 'کریڈٹ کنٹرول',
    'sidebar.item.saas': 'ساس (SaaS)',
    'sidebar.item.branches_pos': 'برانچز',
    'sidebar.item.currencies': 'کرنسی مینیجمنٹ',
    'sidebar.item.approvals': 'ایپروولز',
    'sidebar.item.regions': 'علاقے',
    'sidebar.item.users': 'صارفین اور اختیارات',
    'sidebar.item.health': 'سسٹم ہیلتھ',
    'sidebar.item.wa': 'واٹس ایپ باٹ',
    'sidebar.item.salla_int': 'سلہ انضمام',
    'sidebar.item.sys_settings': 'سیٹنگز',
    'sidebar.item.audit': 'آڈٹ لاگز',
    'sidebar.item.support': 'سپورٹ'
};

const generateObjectCode = (obj) => {
    return Object.entries(obj).map(([k, v]) => `        '${k}': '${v}',`).join('\n');
};

let i18n = fs.readFileSync('src/lib/i18n.tsx', 'utf8');

// First remove any existing old literal overwrites we made earlier (the ones at the top of hi: { ... })
// Actually, it's safer to just inject at the bottom before export function I18nProvider.
// This is perfectly valid Javascript/Typescript and will guarantee it works.

const injectionBlock = `
Object.assign(translations['hi'], {
${generateObjectCode(hiMappings)}
});

Object.assign(translations['bn'], {
${generateObjectCode(bnMappings)}
});

Object.assign(translations['ur'], {
${generateObjectCode(urMappings)}
});
`;

if (!i18n.includes('Object.assign(translations[')) {
    i18n = i18n.replace('export function I18nProvider', injectionBlock + '\nexport function I18nProvider');
    fs.writeFileSync('src/lib/i18n.tsx', i18n, 'utf8');
    console.log('Successfully embedded dynamic dictionary mappings for HI, BN, UR.');
} else {
    console.log('Mappings already exist or file modified previously.');
}
