/**
 * Next.js Edge Middleware — Centralized Auth Guard
 *
 * Protects all /api/* routes except explicitly listed public ones.
 * Runs on Vercel Edge Runtime (before any route handler).
 *
 * Auth flow:
 *   1. Check Authorization header for Bearer token
 *   2. Check `token` cookie as fallback
 *   3. Verify JWT signature
 *   4. If invalid → 401 Unauthorized
 *   5. If valid → allow request to proceed
 *
 * Generated by: remediation/pipeline.py (P0-2)
 */

import { NextRequest, NextResponse } from 'next/server';
import { jwtVerify } from 'jose';

// Routes that do NOT require authentication
const PUBLIC_ROUTES = [
  '/api/auth/login',
  '/api/auth/register',
  '/api/auth/refresh',
  '/api/auth/logout',
  '/api/auth/mfa/verify',
  '/api/health',
  '/api/b2b/auth/login',
  '/api/b2b/auth/register',
  '/api/zatca/callback',
  '/api/webhook',
  '/api/public',
  '/api/pos/session/open',    // POS initial login
];

// Routes outside /api/ that are always public (pages, assets)
const ALWAYS_PUBLIC_PREFIXES = [
  '/_next/',
  '/favicon',
  '/robots',
  '/sitemap',
];

function isPublicRoute(pathname: string): boolean {
  // Non-API routes are always public (handled by Clerk or page-level auth)
  if (!pathname.startsWith('/api/')) return true;

  // Static assets
  if (ALWAYS_PUBLIC_PREFIXES.some(p => pathname.startsWith(p))) return true;

  // Exact public API routes
  if (PUBLIC_ROUTES.some(route => pathname.startsWith(route))) return true;

  return false;
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip non-protected routes
  if (isPublicRoute(pathname)) {
    return NextResponse.next();
  }

  // Extract token from header or cookie
  const authHeader = request.headers.get('authorization');
  let token: string | undefined;

  if (authHeader?.startsWith('Bearer ')) {
    token = authHeader.slice(7);
  } else {
    token = request.cookies.get('token')?.value;
  }

  if (!token) {
    return new NextResponse(
      JSON.stringify({ error: 'Unauthorized', message: 'Authentication required' }),
      { status: 401, headers: { 'Content-Type': 'application/json' } }
    );
  }

  // Verify JWT
  const jwtSecret = process.env.JWT_SECRET;
  if (!jwtSecret) {
    console.error('CRITICAL: JWT_SECRET not set in environment');
    return new NextResponse(
      JSON.stringify({ error: 'Server configuration error' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }

  try {
    const secret = new TextEncoder().encode(jwtSecret);
    const { payload } = await jwtVerify(token, secret);

    // Forward user info to route handlers via headers
    const requestHeaders = new Headers(request.headers);
    requestHeaders.set('x-user-id', String(payload.userId ?? ''));
    requestHeaders.set('x-user-role', String(payload.role ?? ''));
    requestHeaders.set('x-tenant-id', String(payload.tenantId ?? ''));
    requestHeaders.set('x-username', String(payload.username ?? ''));

    return NextResponse.next({ request: { headers: requestHeaders } });
  } catch {
    return new NextResponse(
      JSON.stringify({ error: 'Unauthorized', message: 'Invalid or expired token' }),
      { status: 401, headers: { 'Content-Type': 'application/json' } }
    );
  }
}

// Only run middleware on API routes to avoid overhead on pages
export const config = {
  matcher: [
    '/api/:path*',
  ],
};
