/**
 * @type {import('@stryker-mutator/api/core').PartialStrykerOptions}
 */
module.exports = {
  _comment:
    "This config was generated by Stryker. Configure mutation testing here.",
  packageManager: "npm",
  reporters: ["html", "clear-text", "progress", "dashboard"],
  testRunner: "jest",
  coverageAnalysis: "perTest",
  mutate: [
    "src/lib/auto-journal.ts",
    "src/lib/api/with-route.ts",
    "src/lib/prisma.ts",
    "src/lib/governance/tenant-guard.ts",
    "src/lib/decimal-utils.ts",
    "src/lib/financial-statements-engine.ts",
    "src/lib/credit-check-engine.ts",
    "src/lib/pdpl-engine.ts",
    "src/lib/wht-engine.ts"
  ],
  thresholds: { high: 90, low: 80, break: 80 },
};
