var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/categories/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__f6c62c1d._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_categories_[id]_route_actions_521bfe4c.js")
R.m(248001)
module.exports=R.m(248001).exports
