var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/audit-logs/route.js")
R.c("server/chunks/[root-of-the-server]__3d173a6f._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_audit-logs_route_actions_5e32e0b0.js")
R.m(759005)
module.exports=R.m(759005).exports
