var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/telegram/webhook/route.js")
R.c("server/chunks/src_lib_telegram-bot_ts_5da89743._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__b11f2816._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_next-internal_server_app_api_telegram_webhook_route_actions_1710f968.js")
R.m(888178)
module.exports=R.m(888178).exports
