var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/purchases/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_a2cef4cd.js")
R.c("server/chunks/[root-of-the-server]__836dc9d2._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_next-internal_server_app_api_purchases_route_actions_e0a6c739.js")
R.m(964202)
module.exports=R.m(964202).exports
