var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/fng/budgets/route.js")
R.c("server/chunks/[root-of-the-server]__248e63f7._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_fng_budgets_route_actions_8397230a.js")
R.m(786076)
module.exports=R.m(786076).exports
