var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/hr/evaluations/route.js")
R.c("server/chunks/[root-of-the-server]__da5a43a1._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_hr_evaluations_route_actions_36cc56cb.js")
R.m(128894)
module.exports=R.m(128894).exports
