var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/cfo/route.js")
R.c("server/chunks/[root-of-the-server]__0e87ec61._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_@google_generative-ai_dist_index_mjs_2be827c7._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_cfo_route_actions_2f3e7950.js")
R.m(364595)
module.exports=R.m(364595).exports
