var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/bnpl/tabby/route.js")
R.c("server/chunks/[root-of-the-server]__de112a45._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/_next-internal_server_app_api_bnpl_tabby_route_actions_267fdc47.js")
R.m(421179)
module.exports=R.m(421179).exports
