var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ice/toggle/route.js")
R.c("server/chunks/[root-of-the-server]__9bfd9d4f._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_cd2e74dc._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/_next-internal_server_app_api_ice_toggle_route_actions_5b57dca4.js")
R.m(296428)
module.exports=R.m(296428).exports
