var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/bnpl/tamara/route.js")
R.c("server/chunks/[root-of-the-server]__b42996a8._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/_next-internal_server_app_api_bnpl_tamara_route_actions_1f3bb4d0.js")
R.m(928650)
module.exports=R.m(928650).exports
