import { _t } from '@/lib/server-t';
'use client';
import { useState, useEffect } from 'react';
import { Wrench, Plus } from 'lucide-react';
import { useToast } from '@/components/Toast';
import { useTranslation } from '@/lib/i18n';
export default function WorkOrdersPage() {
  const { error: te, success: ts } = useToast();
  const { lang } = useTranslation();
  const _t = (ar: string, en: string) => lang === 'ar' ? ar : en;
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState<any>({priority:'MEDIUM',description:'',cost:0});
  useEffect(() => { load(); }, []);
  const load = async () => { setLoading(true); try { const r = await fetch('/api/cmms/work-orders',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); if(r.ok) setItems(await r.json()); } catch{} finally { setLoading(false); } };
  const save = async (e:React.FormEvent) => { e.preventDefault(); try { await fetch('/api/cmms/work-orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`},body:JSON.stringify(form)}); ts(_t('تم','Saved')); setShowModal(false); load(); } catch(e:any){te(e?.message);} };
  const pc:any = {LOW:'#22C55E',MEDIUM:'#EAB308',HIGH:'#F97316',CRITICAL:'#EF4444'};
  const pl:any = {LOW:_t('منخفضة','Low'),MEDIUM:_t('متوسطة','Medium'),HIGH:_t('عالية','High'),CRITICAL:_t('حرجة','Critical')};
  const sc:any = {OPEN:'#3B82F6',IN_PROGRESS:'#EAB308',COMPLETED:'#22C55E',CANCELLED:'#94A3B8'};
  const sl:any = {OPEN:_t('مفتوح','Open'),IN_PROGRESS:_t('جاري','In Progress'),COMPLETED:_t('مكتمل','Completed'),CANCELLED:_t('ملغي','Cancelled')};
  return (<div style={{padding:'24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px',flexWrap:'wrap',gap:'16px'}}><div><h1 style={{fontSize:'24px',fontWeight:'bold',display:'flex',alignItems:'center',gap:'10px'}}><Wrench size={28} color="var(--primary)"/> {_t('أوامر الصيانة','Maintenance Work Orders')}</h1><p style={{color:'var(--text-muted)',marginTop:'4px',fontSize:'14px'}}>{_t('CMMS - أوامر الصيانة والإصلاح','CMMS - Maintenance & Repair Orders')}</p></div><button className="btn btn-primary" onClick={()=>{setForm({priority:'MEDIUM',description:'',cost:0});setShowModal(true);}}><Plus size={20}/> {_t('أمر عمل جديد','New Work Order')}</button></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(160px,1fr))',gap:'16px',marginBottom:'24px'}}>{[{l:_t('مفتوحة','Open'),v:items.filter(i=>i.status==='OPEN').length,c:'#3B82F6'},{l:_t('جارية','In Progress'),v:items.filter(i=>i.status==='IN_PROGRESS').length,c:'#EAB308'},{l:_t('مكتملة','Completed'),v:items.filter(i=>i.status==='COMPLETED').length,c:'#22C55E'},{l:_t('التكلفة','Cost'),v:items.reduce((a:number,i:any)=>a+(i.cost||0),0).toLocaleString()+` ${_t('ر.س','SAR')}`,c:'#6366F1'}].map((s,i)=>(<div key={i} className="card" style={{padding:'16px',borderTop:`3px solid ${s.c}`}}><div style={{fontSize:'12px',color:'var(--text-muted)'}}>{s.l}</div><div style={{fontSize:'24px',fontWeight:'800',color:s.c,marginTop:'4px'}}>{s.v}</div></div>))}</div>
  {loading?<div style={{textAlign:'center',padding:'40px'}}>{_t('جاري التحميل...','Loading...')}</div>:(<div className="card" style={{overflow:'auto'}}><table className="table"><thead><tr><th>{_t('الوصف','Description')}</th><th>{_t('الأولوية','Priority')}</th><th>{_t('الحالة','Status')}</th><th>{_t('التكلفة','Cost')}</th><th>{_t('التاريخ','Date')}</th></tr></thead><tbody>{items.map(i=>(<tr key={i.id}><td>{i.description||'-'}</td><td><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:(pc[i.priority]||'#94A3B8')+'20',color:pc[i.priority]}}>{pl[i.priority]||i.priority}</span></td><td><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:(sc[i.status]||'#94A3B8')+'20',color:sc[i.status]}}>{sl[i.status]||i.status}</span></td><td>{i.cost} {_t('ر.س','SAR')}</td><td style={{fontSize:'12px'}}>{new Date(i.createdAt).toLocaleDateString(lang==='ar'?'ar-SA':'en-US')}</td></tr>))}{items.length===0&&<tr><td colSpan={5} style={{textAlign:'center',padding:'30px',color:'var(--text-muted)'}}>{_t('لا توجد أوامر عمل','No work orders')}</td></tr>}</tbody></table></div>)}
  {showModal&&(<div className="modal-overlay"><div className="modal-content" style={{maxWidth:'500px'}}><div className="modal-header"><h2>{_t('أمر عمل جديد','New Work Order')}</h2><button className="btn btn-ghost" onClick={()=>setShowModal(false)}>✕</button></div><div className="modal-body"><form onSubmit={save}><div className="input-group"><label className="input-label">{_t('الوصف','Description')}*</label><textarea className="input" rows={3} required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="grid-2"><div className="input-group"><label className="input-label">{_t('الأولوية','Priority')}</label><select className="input" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="LOW">{_t('منخفضة','Low')}</option><option value="MEDIUM">{_t('متوسطة','Medium')}</option><option value="HIGH">{_t('عالية','High')}</option><option value="CRITICAL">{_t('حرجة','Critical')}</option></select></div><div className="input-group"><label className="input-label">{_t('التكلفة','Cost')}</label><input className="input" type="number" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:'12px',marginTop:'20px'}}><button type="button" className="btn btn-ghost" onClick={()=>setShowModal(false)}>{_t('إلغاء','Cancel')}</button><button type="submit" className="btn btn-primary">{_t('حفظ','Save')}</button></div></form></div></div></div>)}</div>);
}
