import { _t } from '@/lib/server-t';
'use client';
import { useState, useEffect } from 'react';
import { BookOpen, Plus, Search, Eye, ThumbsUp } from 'lucide-react';
import { useToast } from '@/components/Toast';
import { useTranslation } from '@/lib/i18n';
export default function KnowledgeBase() {
  const { error: te, success: ts } = useToast();
  const { lang } = useTranslation();
  const _t = (ar: string, en: string) => lang === 'ar' ? ar : en;
  const [articles, setArticles] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [search, setSearch] = useState('');
  const [form, setForm] = useState<any>({ title: '', content: '', tags: '', status: 'DRAFT' });
  useEffect(() => { load(); }, []);
  const load = async () => { setLoading(true); try { const r = await fetch('/api/knowledge/articles',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); if(r.ok) setArticles(await r.json()); } catch{} finally { setLoading(false); } };
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { const r = await fetch('/api/knowledge/articles',{method:form.id?'PUT':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`},body:JSON.stringify(form)}); if(r.ok){ts(_t('تم الحفظ','Saved'));setShowModal(false);load();} } catch(e:any){te(e?.message);} };
  const filtered = articles.filter(a => !search || a.title?.toLowerCase().includes(search.toLowerCase()) || a.tags?.toLowerCase().includes(search.toLowerCase()));
  return (<div style={{padding:'24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px',flexWrap:'wrap',gap:'16px'}}><div><h1 style={{fontSize:'24px',fontWeight:'bold',display:'flex',alignItems:'center',gap:'10px'}}><BookOpen size={28} color="var(--primary)"/>{_t('قاعدة المعرفة','Knowledge Base')}</h1><p style={{color:'var(--text-muted)',marginTop:'4px',fontSize:'14px'}}>{_t('المقالات والأدلة المرجعية','Articles & Reference Guides')}</p></div><button className="btn btn-primary" onClick={()=>{setForm({title:'',content:'',tags:'',status:'DRAFT'});setShowModal(true);}}><Plus size={20}/>{_t('مقالة جديدة','New Article')}</button></div>
  <div style={{position:'relative',marginBottom:'20px'}}><Search size={18} style={{position:'absolute',right:'12px',top:'12px',color:'var(--text-muted)'}}/><input className="input" placeholder={_t('ابحث في المقالات...','Search articles...')} value={search} onChange={e=>setSearch(e.target.value)} style={{paddingRight:'40px'}}/></div>
  {loading?<div style={{textAlign:'center',padding:'40px',color:'var(--text-muted)'}}>{_t('جاري التحميل...','Loading...')}</div>:(<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(320px,1fr))',gap:'16px'}}>{filtered.map(a=>(<div key={a.id} className="card" style={{padding:'20px',cursor:'pointer',transition:'all 0.2s'}} onClick={()=>{setForm(a);setShowModal(true);}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:'8px'}}><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:a.status==='PUBLISHED'?'#22C55E20':'#EAB30820',color:a.status==='PUBLISHED'?'#22C55E':'#EAB308'}}>{a.status==='PUBLISHED'?_t('منشور','Published'):_t('مسودة','Draft')}</span></div><h3 style={{fontSize:'16px',fontWeight:'700',marginBottom:'8px'}}>{a.title}</h3><p style={{fontSize:'13px',color:'var(--text-muted)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{a.content?.substring(0,100)}</p><div style={{display:'flex',gap:'16px',marginTop:'12px',fontSize:'12px',color:'var(--text-muted)'}}><span style={{display:'flex',alignItems:'center',gap:'4px'}}><Eye size={12}/>{a.views}</span><span style={{display:'flex',alignItems:'center',gap:'4px'}}><ThumbsUp size={12}/>{a.helpful}</span></div></div>))}{filtered.length===0&&<div className="card" style={{padding:'40px',textAlign:'center',color:'var(--text-muted)',gridColumn:'1/-1'}}>{_t('لا توجد مقالات','No articles')}</div>}</div>)}
  {showModal&&(<div className="modal-overlay"><div className="modal-content" style={{maxWidth:'700px'}}><div className="modal-header"><h2 style={{fontSize:'18px',fontWeight:'bold'}}>{form.id?_t('تعديل المقالة','Edit Article'):_t('مقالة جديدة','New Article')}</h2><button className="btn btn-ghost" onClick={()=>setShowModal(false)}>✕</button></div><div className="modal-body"><form onSubmit={save}><div className="input-group"><label className="input-label">{_t('العنوان','Title')} *</label><input className="input" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="input-group"><label className="input-label">{_t('المحتوى','Content')} *</label><textarea className="input" rows={8} required value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></div><div className="grid-2"><div className="input-group"><label className="input-label">{_t('الكلمات المفتاحية','Tags')}</label><input className="input" value={form.tags||''} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="tag1, tag2"/></div><div className="input-group"><label className="input-label">{_t('الحالة','Status')}</label><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="DRAFT">{_t('مسودة','Draft')}</option><option value="PUBLISHED">{_t('منشور','Published')}</option></select></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:'12px',marginTop:'20px'}}><button type="button" className="btn btn-ghost" onClick={()=>setShowModal(false)}>{_t('إلغاء','Cancel')}</button><button type="submit" className="btn btn-primary">{_t('حفظ','Save')}</button></div></form></div></div></div>)}</div>);
}
