var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/purchase-returns/route.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_6231ecd5.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__4f6b9d8d._.js")
R.c("server/chunks/_next-internal_server_app_api_purchase-returns_route_actions_731b81e8.js")
R.m(591592)
module.exports=R.m(591592).exports
