var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/purchases/letters-of-credit/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__02866b4e._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/ce889_server_app_api_purchases_letters-of-credit_[id]_route_actions_d7fb513e.js")
R.m(57556)
module.exports=R.m(57556).exports
