var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/sync/route.js")
R.c("server/chunks/[root-of-the-server]__9f0da24f._.js")
R.c("server/chunks/node_modules_56eb36b6._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_server_clerkClient_2d07f23a.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_sync_route_actions_917f06ab.js")
R.m(594396)
module.exports=R.m(594396).exports
