'use client';
import { useState, useEffect } from 'react';
import { useTranslation } from '@/lib/i18n';
import { Wrench, Plus, Calendar } from 'lucide-react';
import { useToast } from '@/components/Toast';
export default function CMSSPage() {
  const { lang } = useTranslation();
  const _t = (ar: string, en: string) => lang === 'ar' ? ar : en;
  const { error: te, success: ts } = useToast();
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState<any>({assetName:'',type:'PREVENTIVE',frequency:'MONTHLY',nextDate:'',assignedTo:''});
  useEffect(() => { load(); }, []);
  const load = async () => { setLoading(true); try { const r = await fetch('/api/cmms/schedules',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}); if(r.ok) setItems(await r.json()); } catch{} finally { setLoading(false); } };
  const save = async (e:React.FormEvent) => { e.preventDefault(); try { await fetch('/api/cmms/schedules',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`},body:JSON.stringify(form)}); ts('تم'); setShowModal(false); load(); } catch(e:any){te(e?.message);} };
  const tc:any = {PREVENTIVE:'#3B82F6',CORRECTIVE:'#EF4444',PREDICTIVE:'#8B5CF6'};
  return (<div style={{padding:'24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px',flexWrap:'wrap',gap:'16px'}}><div><h1 style={{fontSize:'24px',fontWeight:'bold',display:'flex',alignItems:'center',gap:'10px'}}><Wrench size={28} color="var(--primary)" /> إدارة الصيانة (CMMS)</h1><p style={{color:'var(--text-muted)',marginTop:'4px',fontSize:'14px'}}>جداول الصيانة الوقائية والتصحيحية</p></div><button className="btn btn-primary" onClick={()=>{setForm({assetName:'',type:'PREVENTIVE',frequency:'MONTHLY',nextDate:'',assignedTo:''});setShowModal(true);}}><Plus size={20}/> جدول جديد</button></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:'16px',marginBottom:'24px'}}>{[{l:'إجمالي الجداول',v:items.length,c:'#6366F1'},{l:'وقائية',v:items.filter(i=>i.type==='PREVENTIVE').length,c:'#3B82F6'},{l:'تصحيحية',v:items.filter(i=>i.type==='CORRECTIVE').length,c:'#EF4444'},{l:'تنبؤية',v:items.filter(i=>i.type==='PREDICTIVE').length,c:'#8B5CF6'}].map((s,i)=>(<div key={i} className="card" style={{padding:'16px',borderTop:`3px solid ${s.c}`}}><div style={{fontSize:'12px',color:'var(--text-muted)'}}>{s.l}</div><div style={{fontSize:'28px',fontWeight:'800',color:s.c,marginTop:'4px'}}>{s.v}</div></div>))}</div>
  {loading?<div style={{textAlign:'center',padding:'40px'}}>جاري التحميل...</div>:(<div className="card" style={{overflow:'auto'}}><table className="table"><thead><tr><th>الأصل</th><th>النوع</th><th>التكرار</th><th>القادم</th><th>المسؤول</th><th>الحالة</th><th>أوامر</th></tr></thead><tbody>{items.map(i=>(<tr key={i.id}><td style={{fontWeight:'600'}}>{i.assetName||'-'}</td><td><span style={{padding:'2px 8px',borderRadius:'8px',fontSize:'11px',fontWeight:'600',background:(tc[i.type]||'#94A3B8')+'20',color:tc[i.type]}}>{i.type==='PREVENTIVE'?'وقائية':i.type==='CORRECTIVE'?'تصحيحية':'تنبؤية'}</span></td><td>{i.frequency}</td><td>{i.nextDate?new Date(i.nextDate).toLocaleDateString('ar-SA'):'-'}</td><td>{i.assignedTo||'-'}</td><td>{i.status}</td><td>{i._count?.workOrders||0}</td></tr>))}{items.length===0&&<tr><td colSpan={7} style={{textAlign:'center',padding:'30px',color:'var(--text-muted)'}}>لا توجد جداول</td></tr>}</tbody></table></div>)}
  {showModal&&(<div className="modal-overlay"><div className="modal-content" style={{maxWidth:'500px'}}><div className="modal-header"><h2>جدول صيانة جديد</h2><button className="btn btn-ghost" onClick={()=>setShowModal(false)}>✕</button></div><div className="modal-body"><form onSubmit={save}><div className="grid-2"><div className="input-group" style={{gridColumn:'1/-1'}}><label className="input-label">اسم الأصل*</label><input className="input" required value={form.assetName} onChange={e=>setForm({...form,assetName:e.target.value})}/></div><div className="input-group"><label className="input-label">النوع</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="PREVENTIVE">وقائية</option><option value="CORRECTIVE">تصحيحية</option><option value="PREDICTIVE">تنبؤية</option></select></div><div className="input-group"><label className="input-label">التكرار</label><select className="input" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="DAILY">يومي</option><option value="WEEKLY">أسبوعي</option><option value="MONTHLY">شهري</option><option value="QUARTERLY">ربع سنوي</option><option value="YEARLY">سنوي</option></select></div><div className="input-group"><label className="input-label">الصيانة القادمة</label><input className="input" type="date" value={form.nextDate} onChange={e=>setForm({...form,nextDate:e.target.value})}/></div><div className="input-group"><label className="input-label">المسؤول</label><input className="input" value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}/></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:'12px',marginTop:'20px'}}><button type="button" className="btn btn-ghost" onClick={()=>setShowModal(false)}>إلغاء</button><button type="submit" className="btn btn-primary">حفظ</button></div></form></div></div></div>)}</div>);
}
