var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/b2b/login/route.js")
R.c("server/chunks/[root-of-the-server]__c7535e63._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/_next-internal_server_app_api_b2b_login_route_actions_2fb07257.js")
R.m(913181)
module.exports=R.m(913181).exports
