var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/finance/petty-cash/[id]/process/route.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__396482fb._.js")
R.c("server/chunks/[root-of-the-server]__55b585d3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/ce889_server_app_api_finance_petty-cash_[id]_process_route_actions_301d82bc.js")
R.m(67056)
module.exports=R.m(67056).exports
